len_python = len('python')
len_dragon = len('dragon')
print('Length of python is:', len_python)
print('Length of dragon is:', len_dragon)
print('These words are different in length:', len_python != len_dragon)